addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.4.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"        % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"            % "2.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"       % "2.0")
addSbtPlugin("com.codecommit"    % "sbt-github-actions" % "0.12.0")
